name: action

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: LucasARNAUD02/LucasARNAUD02@master
          with:
            WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
